version: "3.8"
services: 
  rabbitmq:
    image: rabbitmq:3.8.14-management
  basketdb:
    image: redis
  identitydb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  catalogdb:
    image: mongo
  discountdb:
    image: postgres
  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  identityserver.api:
    image: identityserver_api_image
    build:
      context: .
      dockerfile: IdentityServer/FreeCourse.IdentityServer/Dockerfile
  catalog.api:
    image: catalog_api_image
    build:
      context: .
      dockerfile: Services/Catalog/FreeCourse.Services.Catalog/Dockerfile  
  discount.api:
    image: discount_api_image
    build:
      context: .
      dockerfile: Services/Discount/FreeCourse.Services.Discount/Dockerfile
  order.api:
    image: order_api_image
    build:
      context: .
      dockerfile: Services/Order/FreeCourse.Services.Order.API/Dockerfile
  basket.api:
    image: basket_api_image
    build:
      context: .
      dockerfile: Services/Basket/FreeCourse.Services.Basket/Dockerfile
  photostock.api:
    image: photostock_api_image
    build:
      context: .
      dockerfile: Services/PhotoStock/FreeCourse.Services.PhotoStock/Dockerfile
  fakepayment.api:
    image: fakepayment_api_image
    build:
      context: .
      dockerfile: Services/FakePayment/FreeCourse.Services.FakePayment/Dockerfile
  gateway.api:
    image: gateway_api_image
    build:
      context: .
      dockerfile: Gateways/FreeCourse.Gateway/Dockerfile
  frontend.web:
    image: frontend_web_image
    build:
      context: .
      dockerfile: Frontends/FreeCourse.Web/Dockerfile
volumes:
  identitydb_volume:
  catalogdb_volume: 
  discountdb_volume:
  orderdb_volume: